// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/order-service-v1/dto.proto

package orderservice_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrder) Reset() {
	*x = CreateOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrder) ProtoMessage() {}

func (x *CreateOrder) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrder.ProtoReflect.Descriptor instead.
func (*CreateOrder) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{0}
}

type GetOrderById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOrderById) Reset() {
	*x = GetOrderById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderById) ProtoMessage() {}

func (x *GetOrderById) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderById.ProtoReflect.Descriptor instead.
func (*GetOrderById) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{1}
}

type FetchOrdersByUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchOrdersByUserId) Reset() {
	*x = FetchOrdersByUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOrdersByUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrdersByUserId) ProtoMessage() {}

func (x *FetchOrdersByUserId) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrdersByUserId.ProtoReflect.Descriptor instead.
func (*FetchOrdersByUserId) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{2}
}

type CancelOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelOrder) Reset() {
	*x = CancelOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrder) ProtoMessage() {}

func (x *CancelOrder) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrder.ProtoReflect.Descriptor instead.
func (*CancelOrder) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{3}
}

type CreateOrder_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Products []*ProductOrder `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *CreateOrder_Request) Reset() {
	*x = CreateOrder_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrder_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrder_Request) ProtoMessage() {}

func (x *CreateOrder_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrder_Request.ProtoReflect.Descriptor instead.
func (*CreateOrder_Request) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateOrder_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrder_Request) GetProducts() []*ProductOrder {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateOrder_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string      `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status  OrderStatus `protobuf:"varint,2,opt,name=status,proto3,enum=order_service.v1.OrderStatus" json:"status,omitempty"`
}

func (x *CreateOrder_Response) Reset() {
	*x = CreateOrder_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrder_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrder_Response) ProtoMessage() {}

func (x *CreateOrder_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrder_Response.ProtoReflect.Descriptor instead.
func (*CreateOrder_Response) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateOrder_Response) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrder_Response) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNEXPECTED_ORDER_STATUS
}

type GetOrderById_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOrderById_Request) Reset() {
	*x = GetOrderById_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderById_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderById_Request) ProtoMessage() {}

func (x *GetOrderById_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderById_Request.ProtoReflect.Descriptor instead.
func (*GetOrderById_Request) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetOrderById_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderById_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *GetOrderById_Response) Reset() {
	*x = GetOrderById_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderById_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderById_Response) ProtoMessage() {}

func (x *GetOrderById_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderById_Response.ProtoReflect.Descriptor instead.
func (*GetOrderById_Response) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetOrderById_Response) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type FetchOrdersByUserId_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FetchOrdersByUserId_Request) Reset() {
	*x = FetchOrdersByUserId_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOrdersByUserId_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrdersByUserId_Request) ProtoMessage() {}

func (x *FetchOrdersByUserId_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrdersByUserId_Request.ProtoReflect.Descriptor instead.
func (*FetchOrdersByUserId_Request) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FetchOrdersByUserId_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FetchOrdersByUserId_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *FetchOrdersByUserId_Response) Reset() {
	*x = FetchOrdersByUserId_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchOrdersByUserId_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOrdersByUserId_Response) ProtoMessage() {}

func (x *FetchOrdersByUserId_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOrdersByUserId_Response.ProtoReflect.Descriptor instead.
func (*FetchOrdersByUserId_Response) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{2, 1}
}

func (x *FetchOrdersByUserId_Response) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CancelOrder_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *CancelOrder_Request) Reset() {
	*x = CancelOrder_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrder_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrder_Request) ProtoMessage() {}

func (x *CancelOrder_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrder_Request.ProtoReflect.Descriptor instead.
func (*CancelOrder_Request) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CancelOrder_Request) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrder_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelOrder_Response) Reset() {
	*x = CancelOrder_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_order_service_v1_dto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrder_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrder_Response) ProtoMessage() {}

func (x *CancelOrder_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_v1_dto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrder_Response.ProtoReflect.Descriptor instead.
func (*CancelOrder_Response) Descriptor() ([]byte, []int) {
	return file_services_order_service_v1_dto_proto_rawDescGZIP(), []int{3, 1}
}

var File_services_order_service_v1_dto_proto protoreflect.FileDescriptor

var file_services_order_service_v1_dto_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x76, 0x31, 0x2f, 0x64, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x5e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x1a, 0x5c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x64, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x64, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a,
	0x39, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x76, 0x0a, 0x13, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x1a, 0x22, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x3b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x1a, 0x24, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x65, 0x72, 0x65, 0x6e, 0x69, 0x74, 0x65, 0x31, 0x31, 0x2f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2d, 0x76, 0x31, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_order_service_v1_dto_proto_rawDescOnce sync.Once
	file_services_order_service_v1_dto_proto_rawDescData = file_services_order_service_v1_dto_proto_rawDesc
)

func file_services_order_service_v1_dto_proto_rawDescGZIP() []byte {
	file_services_order_service_v1_dto_proto_rawDescOnce.Do(func() {
		file_services_order_service_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_order_service_v1_dto_proto_rawDescData)
	})
	return file_services_order_service_v1_dto_proto_rawDescData
}

var file_services_order_service_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_order_service_v1_dto_proto_goTypes = []interface{}{
	(*CreateOrder)(nil),                  // 0: order_service.v1.CreateOrder
	(*GetOrderById)(nil),                 // 1: order_service.v1.GetOrderById
	(*FetchOrdersByUserId)(nil),          // 2: order_service.v1.FetchOrdersByUserId
	(*CancelOrder)(nil),                  // 3: order_service.v1.CancelOrder
	(*CreateOrder_Request)(nil),          // 4: order_service.v1.CreateOrder.Request
	(*CreateOrder_Response)(nil),         // 5: order_service.v1.CreateOrder.Response
	(*GetOrderById_Request)(nil),         // 6: order_service.v1.GetOrderById.Request
	(*GetOrderById_Response)(nil),        // 7: order_service.v1.GetOrderById.Response
	(*FetchOrdersByUserId_Request)(nil),  // 8: order_service.v1.FetchOrdersByUserId.Request
	(*FetchOrdersByUserId_Response)(nil), // 9: order_service.v1.FetchOrdersByUserId.Response
	(*CancelOrder_Request)(nil),          // 10: order_service.v1.CancelOrder.Request
	(*CancelOrder_Response)(nil),         // 11: order_service.v1.CancelOrder.Response
	(*ProductOrder)(nil),                 // 12: order_service.v1.ProductOrder
	(OrderStatus)(0),                     // 13: order_service.v1.OrderStatus
	(*Order)(nil),                        // 14: order_service.v1.Order
}
var file_services_order_service_v1_dto_proto_depIdxs = []int32{
	12, // 0: order_service.v1.CreateOrder.Request.products:type_name -> order_service.v1.ProductOrder
	13, // 1: order_service.v1.CreateOrder.Response.status:type_name -> order_service.v1.OrderStatus
	14, // 2: order_service.v1.GetOrderById.Response.order:type_name -> order_service.v1.Order
	14, // 3: order_service.v1.FetchOrdersByUserId.Response.orders:type_name -> order_service.v1.Order
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_order_service_v1_dto_proto_init() }
func file_services_order_service_v1_dto_proto_init() {
	if File_services_order_service_v1_dto_proto != nil {
		return
	}
	file_services_order_service_v1_const_proto_init()
	file_services_order_service_v1_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_order_service_v1_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOrdersByUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrder_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrder_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderById_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderById_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOrdersByUserId_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchOrdersByUserId_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrder_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_order_service_v1_dto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrder_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_order_service_v1_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_order_service_v1_dto_proto_goTypes,
		DependencyIndexes: file_services_order_service_v1_dto_proto_depIdxs,
		MessageInfos:      file_services_order_service_v1_dto_proto_msgTypes,
	}.Build()
	File_services_order_service_v1_dto_proto = out.File
	file_services_order_service_v1_dto_proto_rawDesc = nil
	file_services_order_service_v1_dto_proto_goTypes = nil
	file_services_order_service_v1_dto_proto_depIdxs = nil
}
