// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: services/product-storage-v1/api_v1.proto

package productstorage_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductStorageClient is the client API for ProductStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductStorageClient interface {
	GetProductById(ctx context.Context, in *GetProductById_Request, opts ...grpc.CallOption) (*GetProductById_Response, error)
	FetchProducts(ctx context.Context, in *FetchProducts_Request, opts ...grpc.CallOption) (*FetchProducts_Response, error)
}

type productStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewProductStorageClient(cc grpc.ClientConnInterface) ProductStorageClient {
	return &productStorageClient{cc}
}

func (c *productStorageClient) GetProductById(ctx context.Context, in *GetProductById_Request, opts ...grpc.CallOption) (*GetProductById_Response, error) {
	out := new(GetProductById_Response)
	err := c.cc.Invoke(ctx, "/product_storage.v1.ProductStorage/GetProductById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productStorageClient) FetchProducts(ctx context.Context, in *FetchProducts_Request, opts ...grpc.CallOption) (*FetchProducts_Response, error) {
	out := new(FetchProducts_Response)
	err := c.cc.Invoke(ctx, "/product_storage.v1.ProductStorage/FetchProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductStorageServer is the server API for ProductStorage service.
// All implementations must embed UnimplementedProductStorageServer
// for forward compatibility
type ProductStorageServer interface {
	GetProductById(context.Context, *GetProductById_Request) (*GetProductById_Response, error)
	FetchProducts(context.Context, *FetchProducts_Request) (*FetchProducts_Response, error)
	mustEmbedUnimplementedProductStorageServer()
}

// UnimplementedProductStorageServer must be embedded to have forward compatible implementations.
type UnimplementedProductStorageServer struct {
}

func (UnimplementedProductStorageServer) GetProductById(context.Context, *GetProductById_Request) (*GetProductById_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductById not implemented")
}
func (UnimplementedProductStorageServer) FetchProducts(context.Context, *FetchProducts_Request) (*FetchProducts_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchProducts not implemented")
}
func (UnimplementedProductStorageServer) mustEmbedUnimplementedProductStorageServer() {}

// UnsafeProductStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductStorageServer will
// result in compilation errors.
type UnsafeProductStorageServer interface {
	mustEmbedUnimplementedProductStorageServer()
}

func RegisterProductStorageServer(s grpc.ServiceRegistrar, srv ProductStorageServer) {
	s.RegisterService(&ProductStorage_ServiceDesc, srv)
}

func _ProductStorage_GetProductById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductById_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStorageServer).GetProductById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_storage.v1.ProductStorage/GetProductById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStorageServer).GetProductById(ctx, req.(*GetProductById_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductStorage_FetchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchProducts_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStorageServer).FetchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_storage.v1.ProductStorage/FetchProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStorageServer).FetchProducts(ctx, req.(*FetchProducts_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductStorage_ServiceDesc is the grpc.ServiceDesc for ProductStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_storage.v1.ProductStorage",
	HandlerType: (*ProductStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductById",
			Handler:    _ProductStorage_GetProductById_Handler,
		},
		{
			MethodName: "FetchProducts",
			Handler:    _ProductStorage_FetchProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/product-storage-v1/api_v1.proto",
}
