// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/product-storage-v1/dto.proto

package productstorage_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProductById) Reset() {
	*x = GetProductById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductById) ProtoMessage() {}

func (x *GetProductById) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductById.ProtoReflect.Descriptor instead.
func (*GetProductById) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{0}
}

type FetchProducts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchProducts) Reset() {
	*x = FetchProducts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProducts) ProtoMessage() {}

func (x *FetchProducts) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProducts.ProtoReflect.Descriptor instead.
func (*FetchProducts) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{1}
}

type GetProductById_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProductById_Request) Reset() {
	*x = GetProductById_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductById_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductById_Request) ProtoMessage() {}

func (x *GetProductById_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductById_Request.ProtoReflect.Descriptor instead.
func (*GetProductById_Request) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetProductById_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductById_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *GetProductById_Response) Reset() {
	*x = GetProductById_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductById_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductById_Response) ProtoMessage() {}

func (x *GetProductById_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductById_Response.ProtoReflect.Descriptor instead.
func (*GetProductById_Response) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetProductById_Response) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type FetchProducts_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchProducts_Request) Reset() {
	*x = FetchProducts_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchProducts_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProducts_Request) ProtoMessage() {}

func (x *FetchProducts_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProducts_Request.ProtoReflect.Descriptor instead.
func (*FetchProducts_Request) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{1, 0}
}

type FetchProducts_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *FetchProducts_Response) Reset() {
	*x = FetchProducts_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchProducts_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProducts_Response) ProtoMessage() {}

func (x *FetchProducts_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProducts_Response.ProtoReflect.Descriptor instead.
func (*FetchProducts_Response) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{1, 1}
}

func (x *FetchProducts_Response) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type FetchProducts_Request_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country *string `protobuf:"bytes,1,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Limit   int64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  int64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *FetchProducts_Request_Filter) Reset() {
	*x = FetchProducts_Request_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_product_storage_v1_dto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchProducts_Request_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProducts_Request_Filter) ProtoMessage() {}

func (x *FetchProducts_Request_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_storage_v1_dto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProducts_Request_Filter.ProtoReflect.Descriptor instead.
func (*FetchProducts_Request_Filter) Descriptor() ([]byte, []int) {
	return file_services_product_storage_v1_dto_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *FetchProducts_Request_Filter) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *FetchProducts_Request_Filter) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchProducts_Request_Filter) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_services_product_storage_v1_dto_proto protoreflect.FileDescriptor

var file_services_product_storage_v1_dto_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2d, 0x76, 0x31, 0x2f, 0x64, 0x74,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x28, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2d, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x1a, 0x41, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0xc2, 0x01, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x1a, 0x6c, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x61, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x43, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x65, 0x6e, 0x69, 0x74,
	0x65, 0x31, 0x31, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2d, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_product_storage_v1_dto_proto_rawDescOnce sync.Once
	file_services_product_storage_v1_dto_proto_rawDescData = file_services_product_storage_v1_dto_proto_rawDesc
)

func file_services_product_storage_v1_dto_proto_rawDescGZIP() []byte {
	file_services_product_storage_v1_dto_proto_rawDescOnce.Do(func() {
		file_services_product_storage_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_product_storage_v1_dto_proto_rawDescData)
	})
	return file_services_product_storage_v1_dto_proto_rawDescData
}

var file_services_product_storage_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_product_storage_v1_dto_proto_goTypes = []interface{}{
	(*GetProductById)(nil),               // 0: product_storage.v1.GetProductById
	(*FetchProducts)(nil),                // 1: product_storage.v1.FetchProducts
	(*GetProductById_Request)(nil),       // 2: product_storage.v1.GetProductById.Request
	(*GetProductById_Response)(nil),      // 3: product_storage.v1.GetProductById.Response
	(*FetchProducts_Request)(nil),        // 4: product_storage.v1.FetchProducts.Request
	(*FetchProducts_Response)(nil),       // 5: product_storage.v1.FetchProducts.Response
	(*FetchProducts_Request_Filter)(nil), // 6: product_storage.v1.FetchProducts.Request.Filter
	(*Product)(nil),                      // 7: product_storage.v1.Product
}
var file_services_product_storage_v1_dto_proto_depIdxs = []int32{
	7, // 0: product_storage.v1.GetProductById.Response.product:type_name -> product_storage.v1.Product
	7, // 1: product_storage.v1.FetchProducts.Response.products:type_name -> product_storage.v1.Product
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_product_storage_v1_dto_proto_init() }
func file_services_product_storage_v1_dto_proto_init() {
	if File_services_product_storage_v1_dto_proto != nil {
		return
	}
	file_services_product_storage_v1_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_product_storage_v1_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_product_storage_v1_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchProducts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_product_storage_v1_dto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductById_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_product_storage_v1_dto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductById_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_product_storage_v1_dto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchProducts_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_product_storage_v1_dto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchProducts_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_product_storage_v1_dto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchProducts_Request_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_product_storage_v1_dto_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_product_storage_v1_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_product_storage_v1_dto_proto_goTypes,
		DependencyIndexes: file_services_product_storage_v1_dto_proto_depIdxs,
		MessageInfos:      file_services_product_storage_v1_dto_proto_msgTypes,
	}.Build()
	File_services_product_storage_v1_dto_proto = out.File
	file_services_product_storage_v1_dto_proto_rawDesc = nil
	file_services_product_storage_v1_dto_proto_goTypes = nil
	file_services_product_storage_v1_dto_proto_depIdxs = nil
}
