// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/api_gateway_v1/dto.proto

package api_gateway_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignIn) Reset() {
	*x = SignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_v1_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn) ProtoMessage() {}

func (x *SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_v1_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn.ProtoReflect.Descriptor instead.
func (*SignIn) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_v1_dto_proto_rawDescGZIP(), []int{0}
}

type SignIn_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignIn_Request) Reset() {
	*x = SignIn_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_v1_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn_Request) ProtoMessage() {}

func (x *SignIn_Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_v1_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn_Request.ProtoReflect.Descriptor instead.
func (*SignIn_Request) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_v1_dto_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SignIn_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignIn_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignIn_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignIn_Response) Reset() {
	*x = SignIn_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_v1_dto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn_Response) ProtoMessage() {}

func (x *SignIn_Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_v1_dto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn_Response.ProtoReflect.Descriptor instead.
func (*SignIn_Response) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_v1_dto_proto_rawDescGZIP(), []int{0, 1}
}

var File_services_api_gateway_v1_dto_proto protoreflect.FileDescriptor

var file_services_api_gateway_v1_dto_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x76, 0x31, 0x2f, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x22, 0x51, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x1a, 0x3b, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x65, 0x6e, 0x69, 0x74, 0x65, 0x31, 0x31, 0x2f,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x5f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_api_gateway_v1_dto_proto_rawDescOnce sync.Once
	file_services_api_gateway_v1_dto_proto_rawDescData = file_services_api_gateway_v1_dto_proto_rawDesc
)

func file_services_api_gateway_v1_dto_proto_rawDescGZIP() []byte {
	file_services_api_gateway_v1_dto_proto_rawDescOnce.Do(func() {
		file_services_api_gateway_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_api_gateway_v1_dto_proto_rawDescData)
	})
	return file_services_api_gateway_v1_dto_proto_rawDescData
}

var file_services_api_gateway_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_api_gateway_v1_dto_proto_goTypes = []interface{}{
	(*SignIn)(nil),          // 0: api_gateway.v1.SignIn
	(*SignIn_Request)(nil),  // 1: api_gateway.v1.SignIn.Request
	(*SignIn_Response)(nil), // 2: api_gateway.v1.SignIn.Response
}
var file_services_api_gateway_v1_dto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_api_gateway_v1_dto_proto_init() }
func file_services_api_gateway_v1_dto_proto_init() {
	if File_services_api_gateway_v1_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_api_gateway_v1_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_v1_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignIn_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_v1_dto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignIn_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_api_gateway_v1_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_api_gateway_v1_dto_proto_goTypes,
		DependencyIndexes: file_services_api_gateway_v1_dto_proto_depIdxs,
		MessageInfos:      file_services_api_gateway_v1_dto_proto_msgTypes,
	}.Build()
	File_services_api_gateway_v1_dto_proto = out.File
	file_services_api_gateway_v1_dto_proto_rawDesc = nil
	file_services_api_gateway_v1_dto_proto_goTypes = nil
	file_services_api_gateway_v1_dto_proto_depIdxs = nil
}
