// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/order_service_v1/const.proto

package order_service_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_UNEXPECTED_ORDER_STATUS OrderStatus = 0
	OrderStatus_CREATED                 OrderStatus = 1
	OrderStatus_PROCESSING              OrderStatus = 2
	OrderStatus_SUCCESS                 OrderStatus = 3
	OrderStatus_FAILED                  OrderStatus = 4
	OrderStatus_CANCELED                OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNEXPECTED_ORDER_STATUS",
		1: "CREATED",
		2: "PROCESSING",
		3: "SUCCESS",
		4: "FAILED",
		5: "CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"UNEXPECTED_ORDER_STATUS": 0,
		"CREATED":                 1,
		"PROCESSING":              2,
		"SUCCESS":                 3,
		"FAILED":                  4,
		"CANCELED":                5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_order_service_v1_const_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_services_order_service_v1_const_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_order_service_v1_const_proto_rawDescGZIP(), []int{0}
}

var File_services_order_service_v1_const_proto protoreflect.FileDescriptor

var file_services_order_service_v1_const_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2a, 0x6e, 0x0a, 0x0b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x4e, 0x45, 0x58,
	0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x65, 0x6e, 0x69, 0x74, 0x65,
	0x31, 0x31, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_services_order_service_v1_const_proto_rawDescOnce sync.Once
	file_services_order_service_v1_const_proto_rawDescData = file_services_order_service_v1_const_proto_rawDesc
)

func file_services_order_service_v1_const_proto_rawDescGZIP() []byte {
	file_services_order_service_v1_const_proto_rawDescOnce.Do(func() {
		file_services_order_service_v1_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_order_service_v1_const_proto_rawDescData)
	})
	return file_services_order_service_v1_const_proto_rawDescData
}

var file_services_order_service_v1_const_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_order_service_v1_const_proto_goTypes = []interface{}{
	(OrderStatus)(0), // 0: order_service_v1.OrderStatus
}
var file_services_order_service_v1_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_order_service_v1_const_proto_init() }
func file_services_order_service_v1_const_proto_init() {
	if File_services_order_service_v1_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_order_service_v1_const_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_order_service_v1_const_proto_goTypes,
		DependencyIndexes: file_services_order_service_v1_const_proto_depIdxs,
		EnumInfos:         file_services_order_service_v1_const_proto_enumTypes,
	}.Build()
	File_services_order_service_v1_const_proto = out.File
	file_services_order_service_v1_const_proto_rawDesc = nil
	file_services_order_service_v1_const_proto_goTypes = nil
	file_services_order_service_v1_const_proto_depIdxs = nil
}
